// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssrbpfbqrudyyzfmxwfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcmJwZmJxcnVkeXl6Zm14d2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzMwOTMsImV4cCI6MjA3NDA0OTA5M30.mVO43KdIkKd3wEQyrEdw2M8Pypa_ybHuplldZSooijY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});